[[repos]]
repo = "builtin"
hooks = [
  { id = "trailing-whitespace" },
  { id = "end-of-file-fixer" },
  { id = "check-yaml" },
  { id = "check-toml" },
  { id = "mixed-line-ending" },
]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.10"
hooks = [{ id = "ruff-check", args = ["--fix"] }, { id = "ruff-format" }]

# [[repos]]
# repo = "local"
# hooks = [
#   { id = "write-cases", name = "Write cases", entry = "./write_cases.py", language = "system", files = 'cases_config/.+\.toml' },
# ]
