description = "Simple scale."
should_error = false
absolute_tolerance = 1e-06
relative_tolerance = 0.001

[source]
name = "output"
coordinates = [
    [
        10,
        40,
    ],
]

[target]
name = "input"
coordinates = [
    [
        1,
        2,
    ],
]
