invert = false

[[scene.coordinateSystems]]
name = "input"
axes = [{ name = "y", type = "space" }, { name = "x", type = "space" }]

[[scene.coordinateSystems]]
name = "output"
axes = [{ name = "y", type = "space" }, { name = "x", type = "space" }]

[[scene.coordinateTransformations]]
name = "input->output"
input = "input"
output = "output"
type = "bijection"
forward = { type = "translation", translation = [1, 1] }
inverse = { type = "translation", translation = [10, 10] }

[conformance]
description = "Bijection forward."

should_error = false
absolute_tolerance = 1e-6
relative_tolerance = 1e-3

[conformance.source]
name = "output"
coordinates = [[1, 2]]

[conformance.target]
name = "input"
coordinates = [[11, 12]]
