name: CI
on: push

jobs:
  prek:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - run: uv run prek run --all-files

  write_cases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - run: ./dev_scripts/write_cases.py
      - run: git diff --exit-code

  test_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
      - run: ./transformation_conformance.py --no-exit-code -- dev_scripts/null_dingus.py

  test_sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: false

      - run: uv build --sdist
        name: build sdist
      - run: |
          mkdir tmp
          cd tmp
          uv venv .venv
          source .venv/bin/activate
        name: setup venv
      - run: uv pip install ../dist/*.tar.gz
        name: install sdist
        working-directory: tmp
      - run: oztc --no-exit-code -- dev_scripts/null_dingus.py
        working-directory: tmp

  test_wheel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: false

      - run: uv build --wheel
        name: build wheel
      - run: |
          mkdir tmp
          cd tmp
          uv venv .venv
          source .venv/bin/activate
        name: setup venv
      - run:
          uv pip install ../dist/*.whl
        name: install wheel
        working-directory: tmp
      - run: oztc --no-exit-code -- dev_scripts/null_dingus.py
        working-directory: tmp
